
server:
  port: 8901
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8800/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: base-provider